package com.stormweapon.client.weather;

import com.stormweapon.config.StormQuality;

/**
 * Hard per-preset caps for the world-anchored rain field.
 *
 * <p>Rain is generated on a world-aligned cell grid, and only the cells inside {@link #radius()} of
 * the camera are submitted. That keeps the cost proportional to the submitted disc rather than to
 * the storm radius, while streak identity stays attached to the world cell, so walking uncovers new
 * cells instead of dragging one cylinder of rain along with the camera.</p>
 *
 * <p>Every number here is a ceiling, never a target. {@link StormRainRenderer} stops the moment
 * either the streak cap or the vertex cap is reached, so a HIGH storm costs the same whether the
 * player stands in the storm core or at the edge of the transition zone.</p>
 *
 * @param cellSize      edge length in blocks of one world rain cell
 * @param streaksPerCell streak slots generated by one fully weighted cell
 * @param radius        radius in blocks of the submitted cell disc
 * @param columnHeight  vertical period in blocks of the world rain lattice
 * @param splashChecks  bounded near-player surface probes attempted per client tick
 * @param maxStreaks    absolute streak ceiling for one frame
 * @param maxVertices   absolute vertex ceiling for one frame of rain
 */
public record StormRainBudget(
    int cellSize,
    int streaksPerCell,
    float radius,
    float columnHeight,
    int splashChecks,
    int maxStreaks,
    int maxVertices
) {
    /** Vertices emitted per streak billboard. */
    public static final int VERTICES_PER_STREAK = 4;

    public static final StormRainBudget LOW = new StormRainBudget(8, 10, 22.0F, 30.0F, 0, 650, 2_600);
    public static final StormRainBudget MEDIUM = new StormRainBudget(8, 19, 30.0F, 36.0F, 4, 1_650, 6_600);
    public static final StormRainBudget HIGH = new StormRainBudget(8, 28, 40.0F, 44.0F, 8, 3_300, 13_200);
    public static final StormRainBudget ULTRA = new StormRainBudget(8, 38, 50.0F, 52.0F, 12, 6_300, 25_200);

    public static StormRainBudget of(StormQuality quality) {
        return switch (quality) {
            case LOW -> LOW;
            case MEDIUM -> MEDIUM;
            case HIGH -> HIGH;
            case ULTRA -> ULTRA;
        };
    }

    /** Streak ceiling once the vertex budget is taken into account. */
    public int streakCeiling() {
        return Math.min(this.maxStreaks, this.maxVertices / VERTICES_PER_STREAK);
    }

    /**
     * Streak slots one cell generates once the client density slider and the local rain envelope
     * are applied. Never exceeds the preset per-cell cap.
     */
    public float cellStreaks(double density, float envelope, float weight) {
        double scaled = this.streaksPerCell * Math.min(density, 2.0D) * envelope * weight;
        return (float)Math.max(0.0D, Math.min(scaled, this.streaksPerCell));
    }
}
